### ISSUE TITLE
View Deck / View Draw Pile regression

### ISSUE THREAD

**Issue by miketwo** [Vesper-arch/Slay-The-Spire-in-Python#23]
Attempting to view the deck or draw pile produces the following error: 
```
Traceback (most recent call last):
  File "/home/runner/Slay-The-Spire-in-Python/main.py", line 8, in <module>
    main(seed=args.parse_args().seed)
  File "/home/runner/Slay-The-Spire-in-Python/game.py", line 311, in main
    encounter(game_map)
  File "/home/runner/Slay-The-Spire-in-Python/game.py", line 290, in <lambda>
    normal_combat = lambda map: combat("Normal", map)
                                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/Slay-The-Spire-in-Python/game.py", line 51, in combat
    other_options[action]()
  File "/home/runner/Slay-The-Spire-in-Python/game.py", line 40, in <lambda>
    other_options = {'d': lambda: view.view_piles(player.deck, player, True), 'a': lambda: view.view_piles(player.draw_pile, player, True),
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/Slay-The-Spire-in-Python/helper.py", line 47, in view_piles
    assert condition in keywords, f"The passed condition('{condition}') is not a valid condition."
AssertionError: The passed condition('') is not a valid condition.
```

**Comment by Vesper-arch** [comment]
The `condition` parameter is supposed to be a string for a dictionary containing certain conditions for displaying cards. These functions use the boolean value of `True` so it got caught by the `assert`. The default value is `""` the `.get()` function defaults to `True`.
